### ISSUE TITLE
Falscher Parameter für Color?

### ISSUE THREAD

**Issue by apollo7321** [DJCordhose/buch-machine-learning-notebooks#2]
Wenn ich lokal das komplette Notebook 4 lokal ausführe, bekomme ich bei 

```
fig = plt.figure(1, figsize=(9, 6))

t = np.linspace(-10,10,200) 
plt.plot(t,logf(t),lw=3.,c='k')
plt.xlabel('t')
plt.ylabel('logistic function(t)')
```
Fehler, weil `K` nicht definiert ist. Ich habe in den anderen Beispielen geschaut, dort wird `k` (also kleingeschrieben) verwendet. Damit bekomme ich auch einen Graphen.

Kann sein, dass ich mich irre, da mir noch nicht ganz klar ist, wo `k` überhaupt herkommt.

**Comment by DJCordhose** [comment]
auf Colab geht es auch mit dem großen K, ich hab es aber nun auf das kleine k geändert

https://colab.research.google.com/github/djcordhose/buch-machine-learning-notebooks/blob/master/kap4.ipynb#scrollTo=kaRhnDQaj-VJ

**Comment by apollo7321** [comment]
Vielen Dank für die schnelle Antwort!
