### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.datasets.samples_generator'

### ISSUE THREAD

**Issue by AST9PIR2** [DJCordhose/buch-machine-learning-notebooks#3]
Servus,

wenn ich Colab das erste mal öffne, erscheint bei kap4.ipynb alles richtig.

Führe ich alle Zellen nochmal aus, bekomme ich den Fehler:
ModuleNotFoundError: No module named 'sklearn.datasets.samples_generator'

Scheinbar hat das was mit einer Änderungen bei neueren Versionen von sckit-learn zu tun:
https://www.datasciencelearner.com/no-module-named-sklearn-datasets-samples_generator-solved/

Gelöst wird es durch das weglassen von ".samples_generator":
"from sklearn.datasets import make_moons"

Grüße

**Comment by DJCordhose** [comment]
yo, vielen Dank, hab ich nun so umgebaut
