### ISSUE TITLE
In Kap 4 plot error

### ISSUE THREAD

**Issue by M4rtinB** [DJCordhose/buch-machine-learning-notebooks#5]
In den letzten beiden Plots werden nicht mehr alle daten geplottet, nur noch 2 der 3.
Lustigerweise passiert bei mir lokal das selbe obwohl ich iris.target_names die 3 typen haben und n_classes = 3
wenn ich beim zweitletzten bsp .
n_classes = 3
colors = 'bwr'#['b','y','r']
CMAP = colors#plt.cm.rainbow
plot_step = 0.01

diese Linien nochmal initialisiere (obwohl die "globalen" values von den vorangegangenen Beispielen noch immer gesetzt und richtig sind) werden in den beiden Letzten Plots alle Daten geplotted

**Comment by DJCordhose** [comment]
ich sehe den Effekt und das scheint schon eine Weile kaputt zu sein, ist uns nur nicht aufgefallen. ich bin gerade etwas ratlos, wie man das richtig heil macht...

**Comment by DJCordhose** [comment]
scheint schon richtig zu sein, die Variablen noch einmal neu zu setzen, weil n_classes zwischendrin auf 2 gesetzt wird. Die Tücke der Notebooks
