### ISSUE TITLE
Kap 5 Rekursive Eliminierung nach Modellen

### ISSUE THREAD

**Issue by M4rtinB** [DJCordhose/buch-machine-learning-notebooks#6]
sklearn version 1.0.2

from sklearn.feature_selection import RFE
selector = RFE(clf, 4)  -> TypeError: __init__() takes 2 positional arguments but 3 were given

das Problem kann gelöst werden indem man definiert was der int eigentlich ist den wir übergeben:
https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html#examples-using-sklearn-feature-selection-rfe

selector = RFE(clf, n_features_to_select=4)

**Comment by DJCordhose** [comment]
yo, vielen Dank, die alte API geht tatsächlich nicht mehr und so ist der Stil auch besser
